# Generated by Django 4.2.6 on 2023-10-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.FloatField(db_index=True, verbose_name='V L1 - N')),
                ('v2', models.FloatField(db_index=True, verbose_name='V L2 - N')),
                ('v3', models.FloatField(db_index=True, verbose_name='V L3 - N')),
                ('v13', models.FloatField(db_index=True, verbose_name='V L1 - L3')),
                ('v12', models.FloatField(db_index=True, verbose_name='V L1 - L2')),
                ('v23', models.FloatField(db_index=True, verbose_name='V L2 - L3')),
                ('i1', models.FloatField(db_index=True, verbose_name='I L1')),
                ('i2', models.FloatField(db_index=True, verbose_name='I L2')),
                ('i3', models.FloatField(db_index=True, verbose_name='I L3')),
                ('p1', models.FloatField(db_index=True, verbose_name='P L1')),
                ('p2', models.FloatField(db_index=True, verbose_name='P L2')),
                ('p3', models.FloatField(db_index=True, verbose_name='P L3')),
                ('pa', models.FloatField(db_index=True, verbose_name='PA')),
                ('fp', models.FloatField(db_index=True, verbose_name='FP')),
                ('hz', models.FloatField(db_index=True, verbose_name='Hz')),
                ('created', models.DateTimeField(db_index=True, verbose_name='Fecha de creación')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor', verbose_name='Sensor N°')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
    ]
