# Generated by Django 4.2.6 on 2023-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measures',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
    ]
