# Generated by Django 5.0.1 on 2024-02-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_alter_measures_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measures',
            name='created',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha de creación'),
        ),
    ]
