# Generated by Django 4.2.6 on 2023-10-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('1', 'Tension Monofasica'), ('2', 'Tension trifasica'), ('3', 'Corriente de línea'), ('4', 'Potencia de fase'), ('5', 'Potencia activa'), ('6', 'Factor de potencia'), ('7', 'Frecuencia')], max_length=1, verbose_name='Tipo de alerta')),
                ('level', models.CharField(choices=[('0', 'Low'), ('1', 'High')], max_length=1, verbose_name='Nivel de alerta')),
                ('limit', models.FloatField(verbose_name='Limite')),
                ('status', models.BooleanField(verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de alerta',
                'verbose_name_plural': 'Tipos de alertas',
            },
        ),
        migrations.CreateModel(
            name='EmailNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Correo notificaciones',
                'verbose_name_plural': 'Correos notificaciones',
            },
        ),
    ]
