# Generated by Django 4.2.6 on 2023-10-10 13:56

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Modelo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('imagen_device', stdimage.models.StdImageField(force_min_size=False, unique=True, upload_to='media/device', variations={'option': {'crop': True, 'height': 720, 'width': 720}}, verbose_name='Imagen de equipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Located',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Lugar de instalación')),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, unique=True, upload_to='media/located', variations={'option': {'crop': True, 'height': 720, 'width': 720}}, verbose_name='Imagen de lugar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de marca')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sensor', models.SmallIntegerField(unique=True, verbose_name='Numero sensor')),
                ('detail', models.CharField(blank=True, max_length=256, verbose_name='Detalle')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('alerts', models.ManyToManyField(blank=True, to='alerts.alerts')),
                ('device_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='sensors.device', verbose_name='Equipo')),
                ('located_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='located', to='sensors.located', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='tag_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='sensors.tag', verbose_name='Marca'),
        ),
    ]
