# Generated by Django 5.0.2 on 2024-03-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_statesensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statesensors',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='sensors.sensor', verbose_name='Sensor'),
        ),
    ]
